#!/bin/bash

# Edit below to control the images transition
# export SWWW_TRANSITION_FPS=60
# export SWWW_TRANSITION_STEP=2

# This controls (in seconds) when to switch to the next image
INTERVAL=180

while true; do
	img="$(find "$HOME/wm/wallpaper/" -type f -name '*.png'| shuf -n 1)"
	swww img "$img"
	sleep $INTERVAL
done